// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWdVHWt6Eqd4ac27mnuZvDG_ARPWY_co',
    appId: '1:979478478128:web:f0805d86b9364ae227dcf5',
    messagingSenderId: '979478478128',
    projectId: 'omni-market-16d3a',
    authDomain: 'omni-market-16d3a.firebaseapp.com',
    storageBucket: 'omni-market-16d3a.appspot.com',
    measurementId: 'G-1S2SP156DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDavgyN0wZmmDhqPIk8kFpNuvJDhWR5tIY',
    appId: '1:979478478128:android:23831a91c0134d1c27dcf5',
    messagingSenderId: '979478478128',
    projectId: 'omni-market-16d3a',
    storageBucket: 'omni-market-16d3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbshTB47LHCP8jfoSHHHMyyaVAdTVsGyA',
    appId: '1:979478478128:ios:905d1bdcfaa94dda27dcf5',
    messagingSenderId: '979478478128',
    projectId: 'omni-market-16d3a',
    storageBucket: 'omni-market-16d3a.appspot.com',
    iosBundleId: 'com.example.omniMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbshTB47LHCP8jfoSHHHMyyaVAdTVsGyA',
    appId: '1:979478478128:ios:70694f90e8402a2c27dcf5',
    messagingSenderId: '979478478128',
    projectId: 'omni-market-16d3a',
    storageBucket: 'omni-market-16d3a.appspot.com',
    iosBundleId: 'com.example.omniMarket.RunnerTests',
  );
}
